version: '3.8'

services:
  db:
    image: mysql:8.0.27
    container_name: wf_db
    command: --authentication_policy=mysql_native_password
    restart: "no"
    user: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wildfire

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wf_app
    restart: "no"
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.19
    container_name: wf_web
    restart: "no"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    volumes_from:
      - app
